version: '3'

services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - backend
  api:
    image: vitta-api
    build: .
    networks:
      - backend
    depends_on:
      - db
    ports:
      - "3000:3000"
    links:
      - db

  web-cli:
    image: vitta-api
    networks:
      - backend
    command: sh

volumes:
  db:
    driver: local

networks:
  backend:
    driver: bridge
extra_hosts:
  - "host.docker.internal:host-gateway"